name: flutter_web_2048
description: Starter template of a clean architecture flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.1+1
  flutter_bloc: ^0.21.0
  equatable: ^0.6.0
  get_it: ^3.0.1
  dartz: ^0.8.7
  connectivity: ^0.4.4
  shared_preferences: ^0.5.3+4
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
