name: flutter_web_2048
description: 2048 game made with flutter web framework

version: 1.20.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.1+1
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  equatable: ^0.6.1
  get_it: ^3.0.3
  dartz: ^0.8.7
  connectivity: ^0.4.4
  data_connection_checker: ^0.3.4
  swipedetector: ^1.2.0
  piecemeal: any
  hive: ^1.1.1
  hive_flutter: ^0.2.1
  path_provider: ^1.4.4
  pwa: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
